<?php

function sbl_form_helper_init() {


$module_path = drupal_get_path('module', 'sbl_form_helper');

$path = drupal_get_path_alias($_GET['q']);
$path_array = explode('/', $path);

// Add a JS file to set several field values depending on other field values.
// Conditional fields did not work.
drupal_add_js($module_path . '/js/form_team_match.js');

}

/**
 * Implementaion of hook_form_FORM_ID_alter
 * Alter the node form for team matches
 */
function sbl_form_helper_form_team_match_node_form_alter(&$form, &$form_state, $form_id) {
  // Add board numbering for single games in the team-match node form
  foreach ($form['field_tm_game'][LANGUAGE_NONE] as $delta => $field) {
    if (is_numeric($delta)) {
      $board_number = $delta + 1;
      $form['field_tm_game'][LANGUAGE_NONE][$delta]['#prefix'] = '<span class="board-number game-' . $board_number . '">Brett ' . $board_number . '</span>';
    }
  }




   //Filter the players by team with ajax
//  $form['field_tm_team_1'][LANGUAGE_NONE]['#ajax'] = array (
//    'callback' => 'filter_players_team_1',
//    // Wrapper: reload the entire field collection form when executing the ajax call
//    'wrapper' => 'edit-field-tm-game',
//  );
}

function filter_players_team_1(&$form, &$form_state) {
//    $numbers = array('0', '1', '2', '3', '4', '5', '6', '7');
//  foreach($numbers as $delta) {
//    $players_enable = array('_none', '299', '301', '303');
//    foreach($form['field_tm_game'][LANGUAGE_NONE][$delta]['field_mt_player_1'][LANGUAGE_NONE]['#options'] as $key => $option) {
//      if(!in_array($key, $players_enable)) {
//        unset($form['field_tm_game'][LANGUAGE_NONE][$delta]['field_mt_player_1'][LANGUAGE_NONE]['#options'][$key]);
//      }
//    }
//  }
//
//  return $form['field_tm_game'];
}




