<?php



/**
 * Implements hook_permission().
 */
function sbl_settings_permission() {
  return array(
    'access sbl settings' => array(
      'title' => t('Access the Schachbundesliga settings page'),
    )
  );
}

/**
 * Implements hook_menu().
 */
function sbl_settings_menu() {
  $items['admin/config/system/sbl_settings'] = array(
    'title' => 'Schachbundesliga Einstellungen',
    'description' => 'Example of using the Form API.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('sbl_settings_form'),
    'access callback' => TRUE,
    'weight' => -20,
    'access callback' => 'user_access',
    'access arguments' => array('access sbl settings'),
  );
  return $items;
}

/**
 * A simple form.
 */
function sbl_settings_form($form, &$form_submit) {
    // the select for the matchday
   $form['current_matchday'] = array(
       '#type' => 'select',
       '#title' => 'Aktueller Spieltag 1. Liga',
       '#options' => array(
          1 => 1,
          2 => 2,
          3 => 3,
          4 => 4,
          5 => 5,
          6 => 6,
          7 => 7,
          8 => 8,
          9 => 9,
          10 => 10,
          11 => 11,
          12 => 12,
          13 => 13,
          14 => 14,
          15 => 15,
       ),
        '#empty_value' => '',
        '#description' => 'Setzen Sie den aktuellen Spieltag',
        '#default_value' => variable_get('current_matchday', ''),
   );
   
    $form['current_matchday_fbl'] = array(
       '#type' => 'select',
       '#title' => 'Aktueller Spieltag FBL',
       '#options' => array(
          1 => 1,
          2 => 2,
          3 => 3,
          4 => 4,
          5 => 5,
          6 => 6,
          7 => 7,
          8 => 8,
          9 => 9,
          10 => 10,
          11 => 11,
       ),
        '#empty_value' => '',
        '#description' => 'Setzen Sie den aktuellen Spieltag',
        '#default_value' => variable_get('current_matchday_fbl', ''),
   );
   
   $form['current_matchday_2bl'] = array(
       '#type' => 'select',
       '#title' => 'Aktueller Spieltag der 2. Liga Nord/Süd/West',
       '#options' => array(
          1 => 1,
          2 => 2,
          3 => 3,
          4 => 4,
          5 => 5,
          6 => 6,
          7 => 7,
          8 => 8,
          9 => 9,
       ),
        '#empty_value' => '',
        '#description' => 'Setzen Sie den aktuellen Spieltag',
        '#default_value' => variable_get('current_matchday_2bl', ''),
   );
   
   $form['current_matchday_2bl_ost'] = array(
       '#type' => 'select',
       '#title' => 'Aktueller Spieltag der 2. Liga Ost',
       '#options' => array(
          1 => 1,
          2 => 2,
          3 => 3,
          4 => 4,
          5 => 5,
          6 => 6,
          7 => 7,
          8 => 8,
          9 => 9,
		  10 => 10,
       ),
        '#empty_value' => '',
        '#description' => 'Setzen Sie den aktuellen Spieltag',
        '#default_value' => variable_get('current_matchday_2bl_ost', ''),
   );

  $form['date_matchday'] = array(
    '#type' => 'date_popup',
    '#title' => 'Datum des Spieltages',
    '#date_format' => 'd.m.Y',
    '#date_year_range' => '-1:+1',
    '#date_label_position' => 'none',
    '#default_value' => variable_get('date_matchday', ''),
  );

  // Get the value from the taxonomy vocabulary "Season"
  $saison_vocabulary = $vocabulary = taxonomy_vocabulary_machine_name_load('saison');
  $terms = entity_load('taxonomy_term', FALSE, array('vid' => $vocabulary->vid));
  $season_values = array();
  foreach($terms as $term) {
    $season_values[$term->tid] = $term->name;
  }
  $form['current_season'] = array(
       '#type' => 'select',
       '#title' => 'Aktuelle Saison',
       '#options' => $season_values,
        '#empty_value' => '',
        '#description' => 'Setzen Sie die aktuelle Saison',
        '#default_value' => variable_get('current_season', ''),
   );
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => 'Speichern',
  );

  return $form;
}

  /**
 * Submit function for input_simple_form().
 */
function sbl_settings_form_submit($form, &$form_state) {
  $old_matchday = variable_get('current_matchday', '');
  $old_matchday_fbl = variable_get('current_matchday_fbl', '');
  $old_matchday_2bl = variable_get('current_matchday_2bl', '');
  $old_matchday_2bl_ost = variable_get('current_matchday_2bl_ost', '');
  $old_date_matchday = variable_get('date_matchday', '');
  $old_season_value = variable_get('current_season', '');
  // Save our form values into the database
  variable_set('current_matchday', $form_state['values']['current_matchday']);
  variable_set('current_matchday_fbl', $form_state['values']['current_matchday_fbl']);
  variable_set('current_matchday_2bl', $form_state['values']['current_matchday_2bl']);
  variable_set('current_matchday_2bl_ost', $form_state['values']['current_matchday_2bl_ost']);
  variable_set('date_matchday', $form_state['values']['date_matchday']);
  variable_set('current_season', $form_state['values']['current_season']);
  $current_matchday = variable_get('current_matchday', '');
  $current_matchday_fbl = variable_get('current_matchday_fbl', '');
  $current_matchday_2bl = variable_get('current_matchday_2bl', '');
  $current_matchday_2bl_ost = variable_get('current_matchday_2bl_ost', '');

  // To set a message which year was saved as current season, first get te taxonomy term label
  $saison_vocabulary = $vocabulary = taxonomy_vocabulary_machine_name_load('saison');
  $terms = entity_load('taxonomy_term', FALSE, array('vid' => $vocabulary->vid));
  $season_values = array();
  foreach($terms as $term) {
    $season_values[$term->tid] = $term->name;
  }
  $date_matchday = variable_get('date_matchday', '');
  $date_matchday_object = new DateTime($date_matchday);
  $date_matchday_formatted = date_format($date_matchday_object, 'd.m.Y');
  $current_season_value = variable_get('current_season', '');
  $current_season_label = $season_values[$current_season_value];

  // Set some messages when the form is saved.
  if($current_matchday != $old_matchday) {
    drupal_set_message($current_matchday . ' wurde als aktueller Spieltag der SBL gesetzt');
  }
  if($current_matchday_fbl != $old_matchday_fbl) {
    drupal_set_message($current_matchday_fbl . ' wurde als aktueller Spieltag der FBL gesetzt');
  }
  if($current_matchday_2bl != $old_matchday_2bl) {
    drupal_set_message($current_matchday_2bl . ' wurde als aktueller Spieltag der 2. Liga Nord/Süd/West gesetzt');
  }
  if($current_matchday_2bl_ost != $old_matchday_2bl_ost) {
    drupal_set_message($current_matchday_2bl_ost . ' wurde als aktueller Spieltag der 2. Liga Ost gesetzt');
  }
  if($date_matchday != $old_date_matchday) {
    drupal_set_message($date_matchday_formatted . ' wurde als Datum des Spieltages gesetzt');
  }
  if($current_season_value != $old_season_value) {
    drupal_set_message($current_season_label . ' wurde als aktuelle Saison gesetzt');
  }
}

/**
 * Make the current matchday system-wide available
 */
function get_current_matchday() {
  // Get the current season from the variable table
  // We set it in the form above
  $current_matchday = variable_get('current_matchday', '');
  return $current_matchday;
}

function get_current_matchday_fbl() {
  // Get the current season from the variable table
  // We set it in the form above
  $current_matchday_fbl = variable_get('current_matchday_fbl', '');
  return $current_matchday_fbl;
}

function get_current_matchday_2bl() {
  // Get the current season from the variable table
  // We set it in the form above
  $current_matchday_2bl = variable_get('current_matchday_2bl', '');
  return $current_matchday_2bl;
}

function get_current_matchday_2bl_ost() {
  // Get the current season from the variable table
  // We set it in the form above
  $current_matchday_2bl_ost = variable_get('current_matchday_2bl_ost', '');
  return $current_matchday_2bl_ost;
}

/**
 * Make the matchday date system-wide available
 */
function get_date_matchday() {
  // Get the current season from the variable table
  // We set it in the form above
  $date_matchday = variable_get('date_matchday', '');
  return $date_matchday;
}

/**
 * Make the current season system-wide available
 */
function get_current_season() {
  // Get the current season from the variable table
  // We set it in the form above
  $current_season = variable_get('current_season', '');
  return $current_season;
}