<?php
function sbl_pgn_init() {
	
$path = drupal_get_path_alias($_GET['q']);
$path_array = explode('/', $path);

	if(!drupal_is_front_page() && ($path_array[0]=="spielberichte" || $path_array[0]=="aktuell" || $path_array[0]=="bundesliga" || $path_array[0]=="klubnews")) {
    drupal_add_js('https://pgn.chessbase.com/jquery-3.0.0.min.js', array('type' => 'external', 'scope' => 'footer', 'weight' => 10));
    drupal_add_js('https://pgn.chessbase.com/cbreplay.js', array('type' => 'external', 'scope' => 'footer', 'weight' => 10));
    drupal_add_css('https://pgn.chessbase.com/CBReplay.css', array('type' => 'external', 'scope' => 'footer', 'weight' => 10));
    drupal_add_js('var jq300 = jQuery; jQuery.noConflict(true);',
      array('type' => 'inline', 'scope' => 'footer', 'weight' => 9));
	}
}
/**
 * Formatter Info.
 */
function sbl_pgn_field_formatter_info() {
  return array(
    'sbl_pgn' => array( 
      'label' => t('PGN Formatter'),
      'field types' => array('text_long'), //This will only be available to text long fields
      'description' => t("PGN-Formatter im Chessbase-Stil"),
      ),
  );
}


/**
 * Formatting of the text field
 */
function sbl_pgn_field_formatter_view($entity_type,$entity, $field,$instance,$langcode, $items,$display) {
	foreach($items as $delta => $item) {
		$element[$delta] = array(
	
		'#markup' => '<div class="cbreplay">' . $item['value'] . '</div>',
	);
	}
	return $element;
}
?>