<?php

function sbl_pgn_init() {
	
$path = drupal_get_path_alias($_GET['q']);
$path_array = explode('/', $path);

	if(!drupal_is_front_page() && ($path_array[0]=="spielberichte" || $path_array[0]=="aktuell")) {
		#drupal_add_js('https://pgn.chessbase.com/jquery-3.0.0.min.js', array('type' => 'external', 'scope' => 'header', 'weight' => 1));
		drupal_add_js('https://pgn.chessbase.com/cbreplay.js', array('type' => 'external', 'scope' => 'header', 'weight' => 1));
		drupal_add_css('https://pgn.chessbase.com/CBReplay.css', array('type' => 'external', 'scope' => 'header', 'weight' => 1));

	}
}
/**
 * Implements hook_field_formatter_info().
 */
function sbl_pgn_field_formatter_info() {
  return array(
    'ffe_pgn' => array( //Machine name of the formatter
      'label' => t('PGN Formatter'),
      'field types' => array('text_long'), //This will only be available to text fields
      'description' => t("Testfeld-Formatter"),
      ),
  );
}



/**
 * Implements hook_field_formatter_settings_form().
 */
function sbl_pgn_field_formatter_view($entity_type,$entity, $field,$instance,$langcode, $items,$display) {
	foreach($items as $delta => $item) {
		$element[$delta] = array(
		
		'#markup' => '<div class="cbreplay">' . $item['value'] . '</div>',
	);
	}
	return $element;
}

?>

