<?php

/**
 * Load our includes
 */
include_once('includes/calculate_leaderboard.inc');
include_once('includes/filter_leaderboard.inc');
include_once('includes/calculate_crosstable.inc');
include_once('includes/calculate_players_leaderboard.inc');

/**
 * Write the elo for all players and the current season into an array.
 * Cache this array in drupal_static
 */
function get_player_season_elo($season) {

  $player_elo = '';
  $player_team = '';

  // Get all player nodes
  $players_query = new EntityFieldQuery();

  $players_query->entityCondition('entity_type', 'node')
    ->entityCondition('bundle', 'spieler')
    ->propertyCondition('status', NODE_PUBLISHED)
    // Bypass node access
    ->addTag('DANGEROUS_ACCESS_CHECK_OPT_OUT');

  $players = $players_query->execute();

  // Write all nids of player nodes into an array
  if (isset($players['node'])) {
    $player_nids = array_keys($players['node']);
  }

$player_elo_values = array();
  foreach($player_nids as $nid) {
    $player_wrapper = entity_metadata_wrapper('node', $nid);
    $player_name = $player_wrapper->title->value();

    $player_season_data_ids = array();

    $player_verein_value = $player_wrapper->field_sp_verein->value();
    if (!empty($player_verein_value)) {
      foreach ($player_wrapper->field_sp_verein->value() as $season_data) {
        $player_season_data_ids[] = $season_data->item_id;
      }
    }

    $player_season_data_item_id = '';
    foreach ($player_season_data_ids as $data) {
      $player_season_data_query = new EntityFieldQuery();

      $player_season_data_query->entityCondition('entity_type', 'field_collection_item')
        ->entityCondition('bundle', 'field_sp_verein')
        ->propertyCondition('item_id', $data)
        ->fieldCondition('field_saison', 'tid', $season)
        // Bypass node access
        ->addTag('DANGEROUS_ACCESS_CHECK_OPT_OUT');

      $player_season_data = $player_season_data_query->execute();
      if (isset($player_season_data['field_collection_item'])) {
        foreach ($player_season_data['field_collection_item'] as $season_data) {
          $player_season_data_item_id = $season_data->item_id;
        }
      }
    }
    if(!empty($player_season_data_item_id)) {
      $player_season_data_wrapper = entity_metadata_wrapper('field_collection_item', $player_season_data_item_id);
      $player_elo_value = $player_season_data_wrapper->field_pl_elo->value();
      //dpm($player_season_data_wrapper->value());
      if(!empty($player_elo_value)) {
        $player_elo = $player_elo_value;
      }
      $player_team_value = $player_season_data_wrapper->field_fc_verein->value();
      if(!empty($player_team_value)) {
        $player_team = $player_team_value = $player_season_data_wrapper->field_fc_verein->nid->value();
      }
    }

    $player_elo_values[$nid]['nid'] = $nid;
    $player_elo_values[$nid]['name'] = $player_name;
    $player_elo_values[$nid]['team'] = $player_team;
    $player_elo_values[$nid]['elo'] = $player_elo;
  }
  return $player_elo_values;
}

function sbl_calculate_points_views_pre_build(&$view) {
  if($view->name == 'players_leaderboard' && $view->current_display == 'page') {
    $season = arg(1);

    // Generate the elo list with the function get_player_season_elo
    // and save it into drupal_static
    $elo_list = get_player_season_elo($season);
    dpm($elo_list);

    $players_elo_list = &drupal_static('players_elo_list', $elo_list);


    //$jumma = &drupal_static('ama', 'keinadabei');
  }
}
